# Generated by Django 3.1.3 on 2020-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('disel', 'Disel'), ('petrol', 'Petrol'), ('electric', 'Electric')], max_length=10),
        ),
    ]
