# Generated by Django 3.1.3 on 2020-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20201119_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=120),
        ),
    ]
