# Generated by Django 3.1.3 on 2020-11-21 09:45

from django.db import migrations, models


def update_current_transmissions(apps, schema_editor):
    transmission_model = apps.get_model('qickstart', 'Transmission')
    # qs = transmission_model.objects.filter(type='mech')

    all_qs = transmission_model.objects.all()
    for transmission in all_qs:
        if transmission.type == 'mech':
            transmission.type = 'auto'
        transmission.model_name = 'DSG'

    transmission_model.objects.bulk_update(all_qs, ['type', 'model_name'])


def revert_current_transmissions(apps, schema_editor):
    transmission_model = apps.get_model('qickstart', 'Transmission')
    # qs = transmission_model.objects.filter(type='mech')

    all_qs = transmission_model.objects.all()
    for transmission in all_qs:
        if transmission.type == 'auto':
            transmission.type = 'mech'

    transmission_model.objects.bulk_update(all_qs, ['type', 'model_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20201121_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='model_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RunPython(
            update_current_transmissions,
            revert_current_transmissions
        )
    ]
