# Generated by Django 3.0.8 on 2020-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=30)),
                ('body_length', models.IntegerField()),
                ('wingspan', models.IntegerField()),
            ],
        ),
    ]
